// Export the sPHENIX SPACAL light-collection maps to a C++ header for the solid_spacal hit process.
// Source: calibrations/CEMC/LightCollection/Prototype2Module.xml (loaded by Fun4All_G4_Prototype3.C:289),
//   data_grid_light_guide_efficiency: TH2F, efficiency vs (x, y) position fraction of the fiber in its sub-tower
//   data_grid_fiber_trans:            TH1F, transmission vs position along the fiber (cm, fiber local z)
// Run (in the container): root -l -b -q export_lightmaps.C   (writes ../../source/2.9/hitprocess/solid_spacal_lightmaps.h; then rebuild source/2.9)
// Input: fetch sphenix_ref/Prototype2Module.xml first (see readme).
void export_lightmaps(const char* in = "sphenix_ref/Prototype2Module.xml", const char* out = "../../source/2.9/hitprocess/solid_spacal_lightmaps.h")
{
	TFile* f = TFile::Open(in);
	TH2* h2 = (TH2*) f->Get("data_grid_light_guide_efficiency");
	TH1* h1 = (TH1*) f->Get("data_grid_fiber_trans");
	FILE* o = fopen(out, "w");
	fprintf(o, "// Generated by spacal_proto3/export_lightmaps.C from %s. Do not edit.\n", in);
	fprintf(o, "#ifndef SOLID_SPACAL_LIGHTMAPS_H\n#define SOLID_SPACAL_LIGHTMAPS_H 1\n\n");
	fprintf(o, "namespace solid_spacal_maps {\n\n");
	fprintf(o, "// fixed-width axes: bins 1..n cover [min, max]; contents indexed [ix-1] or [(iy-1)*nx + (ix-1)]\n");
	fprintf(o, "const int    lg_nx = %d;\nconst double lg_xmin = %.17g, lg_xmax = %.17g;\n", h2->GetNbinsX(), h2->GetXaxis()->GetXmin(), h2->GetXaxis()->GetXmax());
	fprintf(o, "const int    lg_ny = %d;\nconst double lg_ymin = %.17g, lg_ymax = %.17g;\n", h2->GetNbinsY(), h2->GetYaxis()->GetXmin(), h2->GetYaxis()->GetXmax());
	fprintf(o, "const double lg_eff[%d] = {\n", h2->GetNbinsX()*h2->GetNbinsY());
	for (int iy = 1; iy <= h2->GetNbinsY(); iy++) {
		fprintf(o, "\t");
		for (int ix = 1; ix <= h2->GetNbinsX(); ix++) fprintf(o, "%.9g, ", h2->GetBinContent(ix, iy));
		fprintf(o, "\n");
	}
	fprintf(o, "};\n\n");
	fprintf(o, "const int    tr_n = %d;\nconst double tr_min = %.17g, tr_max = %.17g;   // cm\n", h1->GetNbinsX(), h1->GetXaxis()->GetXmin(), h1->GetXaxis()->GetXmax());
	fprintf(o, "const double tr_val[%d] = {\n\t", h1->GetNbinsX());
	for (int i = 1; i <= h1->GetNbinsX(); i++) fprintf(o, "%.9g,%s", h1->GetBinContent(i), (i % 10 == 0) ? "\n\t" : " ");
	fprintf(o, "\n};\n\n} // namespace solid_spacal_maps\n\n#endif\n");
	fclose(o);
	printf("wrote %s: TH2 %dx%d, TH1 %d bins [%g, %g] cm\n", out, h2->GetNbinsX(), h2->GetNbinsY(), h1->GetNbinsX(), h1->GetXaxis()->GetXmin(), h1->GetXaxis()->GetXmax());
}
