from init_env import init_environment

# adding ccdb as temporary dependency
# will be removed once the hit process routines are plugins
env = init_environment("qt5 geant4 clhep evio xercesc ccdb mlibrary cadmesh hipo")

# env.Replace(CXX = "/apps/gcc/4.7.2/bin/g++")
# env.Replace(CXX = "/usr/bin/clang++")
#env.Append(CXXFLAGS='-Wno-shorten-64-to-32')
#env.Append(CXXFLAGS='-Wno-sign-conversion')

# added because clhep is still behind clang (5/2015)
if env['PLATFORM'] == 'darwin':
	env.Append(CXXFLAGS='-Wno-absolute-value')

# Hit Processes (additional)
env.Append(CPPPATH = ['hitprocess'])
hitp_sources = Split("""
	hitprocess/solid_ec_ps_hitprocess.cc
	hitprocess/solid_ec_hitprocess.cc	
	hitprocess/solid_gem_hitprocess.cc
	hitprocess/solid_hgc_hitprocess.cc
	hitprocess/solid_lgc_hitprocess.cc
	hitprocess/solid_spd_hitprocess.cc	
	hitprocess/solid_mrpc_hitprocess.cc
	hitprocess/solid_spacal_hitprocess.cc
	hitprocess/uRwell_hitprocess.cc
	hitprocess/uRwell_strip.cc
	hitprocess/uRgroove_hitprocess.cc
	hitprocess/uRgroove_strip.cc
	""")
env.Library(source = hitp_sources, target = "lib/ghitprocess")

#solid_gemc (additional)
env.Append(CPPPATH = 'src')
gemc_sources = Split("""
	solid_gemc.cc""")

# Get GEMC path
import os
gemcpath = os.environ['GEMC']+'/'
env.Append(LIBPATH = gemcpath)
env.Append(LIBS = "gemc")
# LIBPATH here is what GEMC used to link all the libraries to libgemc.so
rpath = env['LIBPATH']

# Include Path
incpath = ['.',gemcpath, gemcpath+'src', gemcpath+'materials',gemcpath+'mirrors',gemcpath+'parameters',gemcpath+'utilities',gemcpath+'detector',gemcpath+'sensitivity',gemcpath+'physics',gemcpath+'fields',gemcpath+'output',gemcpath+'gui/src',gemcpath+'hitprocess', gemcpath+'hitprocess/clas12', gemcpath+'hitprocess/clas12/bdx', gemcpath+'hitprocess/HPS',gemcpath+'hitprocess/injector', gemcpath+'hitprocess/GlueX', gemcpath+'hitprocess/eic']
env.Append(CPPPATH = incpath)

env.Program(source = gemc_sources + hitp_sources, target = "solid_gemc")

#env.Append(LIBPATH = ['lib'])
#env.Prepend(LIBS =  ['gmaterials', 'gmirrors', 'gparameters', 'gutilities', 'gdetector', 'gsensitivity', 'gphysics', 'gfields', 'ghitprocess', 'goutput', 'ggui'])
#env.Program(source = gemc_sources, target = "gemc")


#if env['LIBRARY'] == "static":
	#env.Library(source = gemc_sources, target = "gemc")


#if env['LIBRARY'] == "shared":
	#env.SharedLibrary(source = gemc_sources, target = "gemc")
